### PR TITLE
Use Node 14.17.6

### PR DESCRIPTION
**Pull request by andrewh0**
Upgrading to the next minor version of Node unblocks the next major version upgrade for Create React App.

See also:
- https://www.notion.so/landedinc/Improve-frontend-local-development-dd756f854f854a74895efaef6fdcb3f4#0bbac90a0b4a45bba5f42cb5b154170e
- https://github.com/landedhomes/landed-agent/pull/858

### CODE REVIEW

**Comment by andrewh0** [comment]
Will wait for infrastructure upgrades to be complete before opening this up for review

**Comment by andrewh0** [comment]
I updated my local environment to build and use the image in `development/Dockerfile` and things seem to be working well

**Review by david-landed — APPROVED** [review]
This looks good to me.

One note, the `gonode` Dockerfile uses `landedhomes/pynode:latest` as its base image : https://github.com/landedhomes/gonode/blob/master/buster/Dockerfile#L1
As far as I can tell, only the ETL uses `gonode`. We may want to confirm It works after this upgrade, but we can also defer and file a separate ticket as we would need to build the `gonode` docker image for these changes to take effect.

One final comment, imo, we should create a Jenkins job for building and pushing this type of image. I can help with that if we all agree that is the right place for it

**Comment by andrewh0** [comment]
It might be good at some point to track Node versions through the environment instead of code and use something like [NVM](https://github.com/nvm-sh/nvm) to manage Node versions. This would be similar to what Microsoft does in their VSCode dev container: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3/README.md#installing-nodejs

**Pull request merged**
